gbhistory/blogs/urls.py
from django.urls import path
from .views import post_of_theme, post_detail,\
AddPostView, post_my

app_name = 'blogs'

urlpatterns = [
    path('theme/<slug:slug_theme>', post_of_theme, name='theme'),
    path('theme/<slug:slug_theme>/<slug:slug_post>', post_detail, name='post'),
    path('post_add/', AddPostView.as_view(), name='post_add'),
    path('posts/user/<int:user_id>', post_my, name='post_my'),
]

gbhistory/gbhistory/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path('blogs/', include('blogs.urls')),
    path('profile/', include('users.urls')),
    
]

urlpatterns += static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)

gbhistory/main/urls.py
from django.urls import path

gbhistory/users/urls.py
from django.urls import path

from .views import users_index, UserRegisterView,\
UserLoginView, UserLogoutView, user_info

urlpatterns = [
    path('', users_index, name='profile_index'),
    path('reg/', UserRegisterView.as_view(), name='profile_register'),
    path('login/', UserLoginView.as_view(), name='profile_login'),
    path('logout/', UserLogoutView.as_view(), name='profile_logout'),
    path('info/<int:id>', user_info, name='user_info')
]

gbhistory/users/models.py
from django.db import models

# Create your models here.

gbhistory/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django import forms



class UserRegisterForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        fields = UserCreationForm.Meta.fields + ('email', 'first_name', 'last_name')
    
    def clean_email(self):
        """
        Проверка email на уникальность
        """
        email = self.cleaned_data.get('email')
        username = self.cleaned_data.get('username')
        if email and User.objects.filter(email=email).exclude(username=username).exists():
            raise forms.ValidationError('Такой email уже используется в системе')
        return email
    

    def __init__(self, *args, **kwargs):
        """
        Обновление стилей формы регистрации
        """
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields['username'].widget.attrs.update({"placeholder": '*Login'})
            self.fields['email'].widget.attrs.update({"placeholder": '*Email'})
            self.fields['first_name'].widget.attrs.update({"placeholder": '*Name'})
            self.fields["last_name"].widget.attrs.update({"placeholder": '*Last Name'})
            self.fields['password1'].widget.attrs.update({"placeholder": '*Password'})
            self.fields['password2'].widget.attrs.update({"placeholder": '*Password again'})
            self.fields[field].widget.attrs.update({"class": "form-control"})
            self.fields[field].help_text = None
            self.fields[field].label = ""
        
    

class UserLoginForm(AuthenticationForm):
    """
    Форма авторизации на сайте
    """

    def __init__(self, *args, **kwargs):
        """
        Обновление стилей формы регистрации
        """
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields['username'].widget.attrs['placeholder'] = 'Login'
            self.fields['password'].widget.attrs['placeholder'] = 'Password'
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })
            self.fields[field].help_text = None
            self.fields[field].label = ""

# class ProfileUpdateForm(forms.ModelForm):
#     class Meta:
#         model = UserProfile
#         fields = ('about_you',)

#     def __init__(self, *args, **kwargs):
#         """
#         Обновление стилей формы обновления
#         """
#         super().__init__(*args, **kwargs)
#         for field in self.fields:
#             self.fields[field].widget.attrs.update({
#                 'class': 'form-control',
#                 'autocomplete': 'off'
#             })

gbhistory/users/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView
from django.views.generic.edit import UpdateView
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.models import User
from django.db import transaction

from .forms import UserRegisterForm, UserLoginForm


def users_index(request):

    return render(request, 'html/users_index.html')


def user_info(request, id):
    user = User.objects.get(id=id)

    return render(request, 'html/user_info.html', {
        'user':user,
    })

class UserRegisterView(SuccessMessageMixin, CreateView):

    form_class = UserRegisterForm
    success_url = reverse_lazy('home')
    template_name = 'html/user_register.html'
    success_message = 'Успешная регистрация'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Регистрация на сайте'
        return context
    

class UserLoginView(SuccessMessageMixin, LoginView):
    form_class = UserLoginForm
    template_name = 'html/user_login.html'
    next_page = reverse_lazy('home')
    success_message = 'Добро пожаловать на сайт!'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Авторизация на сайте'
        return context


class UserLogoutView(LogoutView):

    next_page = reverse_lazy('profile_index')


# class ProfileUpdateView(UpdateView):
#     model = UserProfile
#     fields = ["about_you"]
#     template_name = 'html/user_update.html'
#     success_message = 'Успешно'

#     def get_object(self, queryset=None):
#         obj = UserProfile.objects.get(user_id=self.kwargs['pk'])
#         return obj

gbhistory/users/templates/html/user_info.html
{% extends 'html/base.html' %}

{% load static %}



{% block link_block %}
    
    <link rel="stylesheet" href="{% static 'css/user_info.css' %}">
{% endblock link_block %}
    


{% block title %}
    
{% endblock title %}
    


{% block content %}
    <div class="container">
        
        <div class="user">
            
            <table>
                <tr>
                    <th>Имя Фамилия</th>
                    <td>{{ user.first_name }} {{ user.last_name }}</td>
                </tr>
                <tr>
                    <th>Почта</th>
                    <td>{{ user.email }}</td>
                </tr>
                <tr>
                    <th>Логин</th>
                    <td>{{ user.username }}</td>
                </tr>
            </table>
        </div>
            
        </div>

    </div>
{% endblock content %}
    

gbhistory/users/templates/html/user_login.html
{% extends 'html/base.html' %}
{% load static %}


{% block link_block %}
    
{% endblock link_block %}
    

{% block title %}
    {{ title }}
{% endblock title %}
    

{% block content %}
    <div class="container">

        <div class="input_card">
            <form action="#" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Login</button>
            </form>
        </div>

    </div>
{% endblock content %}
    

gbhistory/users/templates/html/user_register.html
{% extends 'html/base.html' %}
{% load static %}


{% block link_block %}
    
{% endblock link_block %}
    

{% block title %}
    {{ title }}
{% endblock title %}
    

{% block content %}
    <div class="container">

        <div class="input_card">
            <form action="#" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">register</button>
            </form>
        </div>
    </div>
{% endblock content %}
    

gbhistory/users/templates/html/users_index.html
{% extends 'html/base.html' %}

{% load static %}



{% block link_block %}
    
    <link rel="stylesheet" href="{% static 'css/users_index.css' %}">
{% endblock link_block %}
    


{% block title %}
    PROFILE
{% endblock title %}
    


{% block content %}
    <div class="container">
        
        <div class="users">
            
            {% if request.user.is_authenticated %}
                <form action="{% url 'user_info' request.user.id %}">
                    <button type="submit">Info Account</button>
                </form>

                <form action="{% url 'blogs:post_add' %}">
                    <button type="submit">Add Post</button>
                </form>

                <form action="{% url 'blogs:post_my' request.user.id %}">
                    <button type="submit">My Post</button>
                </form>

                <form action="{% url 'profile_logout' %}" method="post">
                    {% csrf_token %}
                    <button type="submit">LogOut</button>
                </form>

            {% else %}
                <form action="{% url 'profile_login' %}">
                    <button type="submit">Login</button>
                </form>

                
                <form action="{% url 'profile_register' %}">
                    <button type="submit">Register</button>
                </form>    
            {% endif %}
                
            
        </div>

    </div>
{% endblock content %}
    